### ISSUE TITLE
Regarding Collaborators on DockerHub

### ISSUE THREAD

**Issue by vs1804** [michigan-traffic-lab/Mcity-AV-Challenge#12]
Hello,

While submitting the Docker image, is it needed to add all the participants as collaborators on the private repository? This would require getting Docker Team for all the participants.

Is submission allowed with only two collaborators (Mcity and one team member) on the private repository?

**Comment by zhuhj-tery** [comment]
You don't need to add all the participants as collaborators. You only need to add Mcity as the collaborator so that we can access the Docker image.
