### ISSUE TITLE
Starting location of the AV not consistent.

### ISSUE THREAD

**Issue by hhjj233** [michigan-traffic-lab/Mcity-AV-Challenge#13]
While developing my AV algorithm, I discovered that the initial location of the AV is [124.75..., 15.91...], which does not match the starting location in the route.csv file ([127.14, 16.74]).

This discrepancy raises two main concerns:

1. Is this situation normal and acceptable?

2. If so, can we change the initial starting point of the AV?

**Comment by zhuhj-tery** [comment]
The starting point should be [124.7523096154207, 15.917477574911015] and it cannot be changed. The route.csv file is just a reference trajectory which is used to check if your AV algorithm can track a certain route.

**Comment by hhjj233** [comment]
So, what are the specific trajectory completion functions used in the scoring function? Is the route.csv file selected for evaluation as a reference, or is baseline.csv selected? It appears that the coordinates [124.7523096154207, 15.917477574911015] represent the starting location of the autonomous vehicle (AV) in the baseline.csv file.

**Comment by hhjj233** [comment]
Thx! And how about Vehicle rules checking? It seems that [124.7523096154207, 15.917477574911015] is used by checking for the first frame, like maximum acceleration checking.

**Comment by zhuhj-tery** [comment]
Yes, [124.7523096154207, 15.917477574911015] is the starting point and it will be used to check the vehicle rules. The functions used to check the vehicle rules are already given in the file: utils/vehicle_rule_checking.py.

**Comment by hhjj233** [comment]
Thank you very much for the answer :)
