### ISSUE TITLE
Obstacle avoidance

### ISSUE THREAD

**Issue by Eashwar-S** [michigan-traffic-lab/Mcity-AV-Challenge#14]
Just to confirm, the av need to avoid vehicles only in front of them or it should also look out for vehicles behind them? I noticed that sometimes the simulation stops due to collision with the vehicles moving behind the av. 

If we do need to look out for vehicles behind the av, are we provided that information. Please clarify. Thank you.

**Comment by zhuhj-tery** [comment]
First of all, we expect the ego could avoid collision with all the surrounding vehicle. However, the background vehicle might rear-end the ego vehicle sometimes and this kind of crashes might be unavoidable. It will influence the safety score, but all the participants will encounter similar collisions. So, just try your best to avoid those avoidable crashes. 
In addition, all the surrounding vehicles' information have been provided. So, you should be able to see the following vehicle.
