### ISSUE TITLE
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

### ISSUE THREAD

**Issue by Jihy** [michigan-traffic-lab/Mcity-AV-Challenge#4]
when using the download_test_results.py the access denied problem happens.
`Traceback (most recent call last):
  File "E:\McityAVChallenge\Mcity-AV-Challenge\utils\download_test_results.py", line 33, in <module>
    for page in pages:
  File "D:\Anaconda3\Lib\site-packages\botocore\paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\botocore\paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\botocore\client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\botocore\client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied`

Is the usage or connection not correct? Or provide a tutorial on using this tool?
I'm using the windows conda python to excecute the file, and still failed after using a VPN.

**Comment by hhjj233** [comment]
@zhuhj-tery  could you pls check the permission status again for the team with id m2024305642? I faced the exactly same problem.

**Comment by zhuhj-tery** [comment]
Hi,
It seems your team did not share us with your algorithm. So, there are no evaluation results for your team.

**Comment by hhjj233** [comment]
Thx, will try later.

**Comment by hhjj233** [comment]
BTW, where can we check the leaderboard and the specific weight of the evaluation metrics?
