### ISSUE TITLE
Questions about Jerk Check and Speed Limits

### ISSUE THREAD

**Issue by SafeguardLi** [michigan-traffic-lab/Mcity-AV-Challenge#6]
Hello,

During the algorithm development, the simulation is easily killed by the jerk check. In that case, may I ask you:

1) Will latitudinal or longitudinal jerk be checked? What is the definition of the overall jerk? Will the jerk only consider the next step, i.e. the frequency is 0.1 second?
2) Furthermore, if the vehicle encounters an aggressive cut-in (or aggressive merge at the roundabout), we need to apply an emergency brake which may violate the acceleration/jerk limits to avoid a crash. It is a dilemma and we are wondering if you have any suggestions?
2) What is the speed limit for the connector (junction) on the map? 
3) Is a red light violation also a “killer” in the platform or just a penalty? How about right-turn-on-red (e.g., the third intersection on the route)?
4) Lastly, can we NOT exactly follow the waypoints you provided (but keep the route the same)? And are there any penalties for deviating from the waypoints?

Thank you.

**Comment by zhuhj-tery** [comment]
Hi,
Here are the answers to the questions:

1. Lateral and longitudinal jerk will not be checked, and we will only check the overall jerk. It is defined as the combination of the lateral and longitudinal jerk, which is illustrated as follows:
<img width="138" alt="image" src="https://github.com/michigan-traffic-lab/Mcity-AV-Challenge/assets/69643560/3fa4fe93-5744-4786-bde1-04efc31669a5">

The frequency of checking vehicle dynamics is 10 Hz.

2.  Vehicle dynamics are the hard constraints that should NOT be violated even when facing emergence. Violating vehicle dynamics will result in a high route incompletion rate and significantly affect the overall score, so we suggest prioritizing incorporating this metric and mitigating crash rate with other approaches. 
3. The speed limit of the junction can also be found in the SUMO network file. We suggest you parse the map and obtain the speed limit by yourself.
4. A red light violation isn't critical but will impact the rule compliance score. A right turn on red is acceptable, while the vehicle needs to come to a complete stop and yield to other vehicles with the right of way.
5. Yes, you can. We will not evaluate how well your planning algorithm tracks our example route with waypoints. It only serves as a sample route for your planning algorithm to follow. 

Best regards
