### ISSUE TITLE
Changing main.sh file

### ISSUE THREAD

**Issue by shivam-vashi** [michigan-traffic-lab/Mcity-AV-Challenge#8]
Is it allowed to modify the main.sh file to preprocess some data by running a script once something like this-

```
#!/bin/bash

python3 preprocess_data.py

sleep 1
for i in {1..2000}; do
    echo "iteration number ${i}"
    sleep 1
    python3 main.py
done
```

**Comment by zhuhj-tery** [comment]
It is not allowed to change the "main.sh" file.

**Comment by shivam-vashi** [comment]
Ok, Thank You for the clarification.
